import { Handlee } from "next/font/google";
import "./globals.css";
import Header from "../components/header/Header";
import Footer from "../components/footer/Footer";

const inter = Handlee({ subsets: ["latin"],weight:['400'] });

export const metadata = {
  title: "home page",
  description: "Generated by create next app",
  icons:{
    icon:".\images\bag-shopping-solid.svg"
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
      
        <div className="container">
           <Header/>
           {children}
           <Footer/>
        </div>
        </body>
    </html>
  );
}
